# Generated by Django 5.2.6 on 2025-09-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Enter your Name', max_length=250)),
                ('Age', models.IntegerField(help_text='Enter your age')),
                ('Dob', models.DateField(help_text='Enter your Date of Birth')),
                ('Reg_no', models.IntegerField(help_text='Enter your Registration Number')),
            ],
        ),
    ]
